import type { Workspace } from "./types";
import { getTemplate } from "./templates";

export function renderDocument(
  templateId: string,
  values: Record<string, string>,
  workspace: Workspace
): { title: string; markdown: string; html: string } {
  const template = getTemplate(templateId);
  if (!template) throw new Error("Unknown template");

  const title = `${template.name} — ${workspace.branding.clientName}`;
  const lines: string[] = [
    `# ${template.name}`,
    "",
    `**Client:** ${workspace.branding.clientName}`,
    `**Program:** ${workspace.programName}`,
    `**Prepared by:** ${workspace.branding.firmName}`,
    `**Date:** ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
    "",
    "---",
    "",
  ];

  for (const section of template.sections) {
    lines.push(`## ${section.title}`, "");
    for (const fieldId of section.fieldIds) {
      const field = template.fields.find((f) => f.id === fieldId);
      if (!field) continue;
      const value = (values[fieldId] ?? "").trim() || "_Not provided_";
      lines.push(`### ${field.label}`, "", value, "");
    }
  }

  const markdown = lines.join("\n").trim();
  const html = markdownToHtml(markdown, workspace);
  return { title, markdown, html };
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function markdownToHtml(markdown: string, workspace: Workspace): string {
  const { primaryColor, accentColor, firmName, clientName } = workspace.branding;
  const body = markdown
    .split("\n")
    .map((line) => {
      if (line.startsWith("# "))
        return `<h1>${escapeHtml(line.slice(2))}</h1>`;
      if (line.startsWith("## "))
        return `<h2>${escapeHtml(line.slice(3))}</h2>`;
      if (line.startsWith("### "))
        return `<h3>${escapeHtml(line.slice(4))}</h3>`;
      if (line === "---") return "<hr />";
      if (line.startsWith("**") && line.endsWith("**")) {
        const inner = line.slice(2, -2);
        const [label, val] = inner.split(":**");
        if (val !== undefined)
          return `<p><strong>${escapeHtml(label)}:</strong> ${escapeHtml(val.replace(/^\s*/, ""))}</p>`;
      }
      if (!line.trim()) return "";
      if (line === "_Not provided_") return `<p class="muted">Not provided</p>`;
      return `<p>${escapeHtml(line).replace(/\n/g, "<br />")}</p>`;
    })
    .filter(Boolean)
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(workspace.programName)} — Change Deliverable</title>
  <style>
    :root { --primary: ${primaryColor}; --accent: ${accentColor}; }
    body { font-family: Georgia, "Times New Roman", serif; max-width: 720px; margin: 2rem auto; padding: 0 1.5rem; color: #1e293b; line-height: 1.6; }
    header { border-bottom: 3px solid var(--primary); padding-bottom: 1rem; margin-bottom: 2rem; }
    header .firm { color: var(--primary); font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.08em; }
    header .client { font-size: 1.1rem; color: #64748b; }
    h1 { color: var(--primary); font-size: 1.75rem; }
    h2 { color: var(--primary); font-size: 1.25rem; margin-top: 2rem; border-left: 4px solid var(--accent); padding-left: 0.75rem; }
    h3 { font-size: 1rem; color: #334155; margin-top: 1.25rem; }
    hr { border: none; border-top: 1px solid #e2e8f0; margin: 1.5rem 0; }
    .muted { color: #94a3b8; font-style: italic; }
    footer { margin-top: 3rem; font-size: 0.8rem; color: #94a3b8; }
  </style>
</head>
<body>
  <header>
    <div class="firm">${escapeHtml(firmName)}</div>
    <div class="client">${escapeHtml(clientName)} · ${escapeHtml(workspace.programName)}</div>
  </header>
  ${body}
  <footer>Generated by Change Mgmt Studio · Confidential</footer>
</body>
</html>`;
}

export function downloadFile(
  filename: string,
  content: string,
  mime: string
): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
